## Load Data

In [ ]:
import sys

sys.path.append("../src")

from preprocess import load_data, create_target, select_features, preprocess_features

/Users/AustinZhang/IDS583_Final_Project/notebooks/../src/preprocess.py:48: SyntaxWarning: invalid escape sequence '\d'
  df["term"] = df["term"].str.extract("(\d+)").astype(float)

In [2]:
df_raw = load_data("../data/raw/accepted_2007_to_2018Q4.csv")
df_raw.head()

/Users/AustinZhang/IDS583_Final_Project/notebooks/../src/preprocess.py:6: DtypeWarning: Columns (0,19,49,59,118,129,130,131,134,135,136,139,145,146,147) have mixed types. Specify dtype option on import or set low_memory=False.
  return pd.read_csv(path)

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,...,hardship_payoff_balance_amount,hardship_last_payment_amount,disbursement_method,debt_settlement_flag,debt_settlement_flag_date,settlement_status,settlement_date,settlement_amount,settlement_percentage,settlement_term
0,68407277,NaN,3600.0,3600.0,3600.0,36 months,13.99,123.03,C,C4,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
1,68355089,NaN,24700.0,24700.0,24700.0,36 months,11.99,820.28,C,C1,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
2,68341763,NaN,20000.0,20000.0,20000.0,60 months,10.78,432.66,B,B4,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
3,66310712,NaN,35000.0,35000.0,35000.0,60 months,14.85,829.90,C,C5,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
4,68476807,NaN,10400.0,10400.0,10400.0,60 months,22.45,289.91,F,F1,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
df_raw.shape

(2260701, 151)

## Target Construction & Feature Selection

In [3]:
df = create_target(df_raw)

/Users/AustinZhang/IDS583_Final_Project/notebooks/../src/preprocess.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["default"] = (df["loan_status"] == "Charged Off").astype(int)

In [4]:
df["default"].value_counts(normalize=True)

default
0    0.800374
1    0.199626
Name: proportion, dtype: float64

In [5]:
df = select_features(df)

## Missing Values

In [6]:
df.isnull().mean()

loan_amnt         0.000000
annual_inc        0.000000
fico_range_low    0.000000
dti               0.000278
emp_length        0.058359
home_ownership    0.000000
term              0.000000
purpose           0.000000
default           0.000000
dtype: float64

## Preprocessing

In [7]:
df = preprocess_features(df)
df.head()

,loan_amnt,annual_inc,fico_range_low,dti,emp_length,term,default,home_ownership_MORTGAGE,home_ownership_NONE,home_ownership_OTHER,...,purpose_home_improvement,purpose_house,purpose_major_purchase,purpose_medical,purpose_moving,purpose_other,purpose_renewable_energy,purpose_small_business,purpose_vacation,purpose_wedding
0,3600.0,55000.0,675.0,5.91,10.0,36.0,0,True,False,False,...,False,False,False,False,False,False,False,False,False,False
1,24700.0,65000.0,715.0,16.06,10.0,36.0,0,True,False,False,...,False,False,False,False,False,False,False,True,False,False
2,20000.0,63000.0,695.0,10.78,10.0,60.0,0,True,False,False,...,True,False,False,False,False,False,False,False,False,False
4,10400.0,104433.0,695.0,25.37,3.0,60.0,0,True,False,False,...,False,False,True,False,False,False,False,False,False,False
5,11950.0,34000.0,690.0,10.20,4.0,36.0,0,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [8]:
# save the cleaned data
df.to_csv("../data/processed/loan_clean.csv", index=False)